info:
  application:
    name: '@service.name@'
    description: '@project.description@'
    version: '@project.version@'

server:
  port: 8080

#DataSource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoenix_magic_8_ball
    username: postgres
    password: root

flyway:
  url: '@spring.datasource.url@'
  user: '@spring.datasource.username@'
  password: '@spring.datasource.password@'
  locations: classpath:db/migration

