info:
  application:
    name: '@service.name@'
    description: '@project.description@'
    version: '@project.version@'

server:
  port: 8080

#DataSource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoenix_magic_8_ball
    username: postgres
    password: root

  url: '@spring.datasource.url@'
  user: '@spring.datasource.username@'
  password: '@spring.datasource.password@'
  locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            # If not set then Postgres driver will throw this error
            # Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
            # Even though Hibernate handles it some unnecessary info logs are generated due to this error.
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    validate-on-migrate: false

